---
title: "Anko Investor"
remote_theme: just-the-docs/just-the-docs

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

mermaid:
  version: "9.1.6"

heading_anchors: true

aux_links:
  "Edit these docs on Github":
    - "//github.com/anglo-korean/documentation"
  "Visit Anko Investor":
    - "//anko-investor.com"

aux_links_new_tab: true

footer_content: "Copyright &copy; 2021-2023 Anglo Korean. Creative Commons Zero v1.0 Universal"

kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
